[package]
name = "cdshealpix"
version = "0.2.0"
authors = ["Matthieu Baumann <matthieu.baumann@astro.unistra.fr>", "F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["algorithms", "science"] 
repository = "https://github.com/cds-astro/cds-healpix-python/"
description = """
Python cdshealpix package wrapping code of the cdshealpix crate.
"""

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

[lib]
name = "cdshealpix"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
# The cdshealpix rust crate
healpix = { package = "cdshealpix", git = 'https://github.com/cds-astro/cds-healpix-rust', branch = 'master' }
ndarray = "0.12"
ndarray-parallel = "0.9.0"
numpy = "0.5.0"

[dependencies.pyo3]
version = "0.6"
features = ["extension-module"]